name: Keep Render Service Alive

on:
  schedule:
    # Every 14 minutes
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Send ping to Render service
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://pdf-decryptor-service.onrender.com
